(part "MIMXRT1061DVJ6B"
    (packageRef "BGA196C80P14X14_1200X1200X152")
    (interface
        (port "A1" (symbPinId 1) (portName "VSS_1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "GPIO_EMC_27") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "GPIO_EMC_20") (portType INOUT))
        (port "A4" (symbPinId 4) (portName "GPIO_EMC_17") (portType INOUT))
        (port "A5" (symbPinId 5) (portName "GPIO_EMC_16") (portType INOUT))
        (port "A6" (symbPinId 6) (portName "GPIO_EMC_13") (portType INOUT))
        (port "A7" (symbPinId 7) (portName "GPIO_EMC_40") (portType INOUT))
        (port "A8" (symbPinId 8) (portName "GPIO_B0_06") (portType INOUT))
        (port "A9" (symbPinId 9) (portName "GPIO_B0_07") (portType INOUT))
        (port "A10" (symbPinId 10) (portName "GPIO_B0_11") (portType INOUT))
        (port "A11" (symbPinId 11) (portName "GPIO_B1_00") (portType INOUT))
        (port "A12" (symbPinId 12) (portName "GPIO_B1_08") (portType INOUT))
        (port "A13" (symbPinId 13) (portName "GPIO_B1_09") (portType INOUT))
        (port "A14" (symbPinId 14) (portName "VSS_2") (portType INOUT))
        (port "B1" (symbPinId 15) (portName "GPIO_EMC_15") (portType INOUT))
        (port "B2" (symbPinId 16) (portName "GPIO_EMC_18") (portType INOUT))
        (port "B3" (symbPinId 17) (portName "GPIO_EMC_26") (portType INOUT))
        (port "B4" (symbPinId 18) (portName "GPIO_EMC_19") (portType INOUT))
        (port "B5" (symbPinId 19) (portName "VSS_3") (portType INOUT))
        (port "B6" (symbPinId 20) (portName "GPIO_EMC_14") (portType INOUT))
        (port "B7" (symbPinId 21) (portName "GPIO_EMC_39") (portType INOUT))
        (port "B8" (symbPinId 22) (portName "GPIO_B0_05") (portType INOUT))
        (port "B9" (symbPinId 23) (portName "GPIO_B0_08") (portType INOUT))
        (port "B10" (symbPinId 24) (portName "VSS_4") (portType INOUT))
        (port "B11" (symbPinId 25) (portName "GPIO_B1_01") (portType INOUT))
        (port "B12" (symbPinId 26) (portName "GPIO_B1_07") (portType INOUT))
        (port "B13" (symbPinId 27) (portName "GPIO_B1_10") (portType INOUT))
        (port "B14" (symbPinId 28) (portName "GPIO_B1_15") (portType INOUT))
        (port "C1" (symbPinId 29) (portName "GPIO_EMC_21") (portType INOUT))
        (port "C2" (symbPinId 30) (portName "GPIO_EMC_09") (portType INOUT))
        (port "C3" (symbPinId 31) (portName "GPIO_EMC_36") (portType INOUT))
        (port "C4" (symbPinId 32) (portName "GPIO_EMC_33") (portType INOUT))
        (port "C5" (symbPinId 33) (portName "GPIO_EMC_31") (portType INOUT))
        (port "C6" (symbPinId 34) (portName "GPIO_EMC_30") (portType INOUT))
        (port "C7" (symbPinId 35) (portName "GPIO_EMC_41") (portType INOUT))
        (port "C8" (symbPinId 36) (portName "GPIO_B0_04") (portType INOUT))
        (port "C9" (symbPinId 37) (portName "GPIO_B0_09") (portType INOUT))
        (port "C10" (symbPinId 38) (portName "GPIO_B0_12") (portType INOUT))
        (port "C11" (symbPinId 39) (portName "GPIO_B1_02") (portType INOUT))
        (port "C12" (symbPinId 40) (portName "GPIO_B1_06") (portType INOUT))
        (port "C13" (symbPinId 41) (portName "GPIO_B1_11") (portType INOUT))
        (port "C14" (symbPinId 42) (portName "GPIO_B1_14") (portType INOUT))
        (port "D1" (symbPinId 43) (portName "GPIO_EMC_28") (portType INOUT))
        (port "D2" (symbPinId 44) (portName "GPIO_EMC_25") (portType INOUT))
        (port "D3" (symbPinId 45) (portName "GPIO_EMC_24") (portType INOUT))
        (port "D4" (symbPinId 46) (portName "GPIO_EMC_34") (portType INOUT))
        (port "D5" (symbPinId 47) (portName "GPIO_EMC_32") (portType INOUT))
        (port "D6" (symbPinId 48) (portName "GPIO_EMC_38") (portType INOUT))
        (port "D7" (symbPinId 49) (portName "GPIO_B0_00") (portType INOUT))
        (port "D8" (symbPinId 50) (portName "GPIO_B0_03") (portType INOUT))
        (port "D9" (symbPinId 51) (portName "GPIO_B0_10") (portType INOUT))
        (port "D10" (symbPinId 52) (portName "GPIO_B0_13") (portType INOUT))
        (port "D11" (symbPinId 53) (portName "GPIO_B1_03") (portType INOUT))
        (port "D12" (symbPinId 54) (portName "GPIO_B1_05") (portType INOUT))
        (port "D13" (symbPinId 55) (portName "GPIO_B1_12") (portType INOUT))
        (port "D14" (symbPinId 56) (portName "GPIO_B1_13") (portType INOUT))
        (port "E1" (symbPinId 57) (portName "GPIO_EMC_29") (portType INOUT))
        (port "E2" (symbPinId 58) (portName "VSS_5") (portType INOUT))
        (port "E3" (symbPinId 59) (portName "GPIO_EMC_00") (portType INOUT))
        (port "E4" (symbPinId 60) (portName "GPIO_EMC_37") (portType INOUT))
        (port "E5" (symbPinId 61) (portName "GPIO_EMC_35") (portType INOUT))
        (port "E6" (symbPinId 62) (portName "NVCC_EMC_1") (portType INOUT))
        (port "E7" (symbPinId 63) (portName "GPIO_B0_01") (portType INOUT))
        (port "E8" (symbPinId 64) (portName "GPIO_B0_02") (portType INOUT))
        (port "E9" (symbPinId 65) (portName "NVCC_GPIO_1") (portType INOUT))
        (port "E10" (symbPinId 66) (portName "GPIO_B0_14") (portType INOUT))
        (port "E11" (symbPinId 67) (portName "GPIO_B0_15") (portType INOUT))
        (port "E12" (symbPinId 68) (portName "GPIO_B1_04") (portType INOUT))
        (port "E13" (symbPinId 69) (portName "VSS_6") (portType INOUT))
        (port "E14" (symbPinId 70) (portName "GPIO_AD_B0_06") (portType INOUT))
        (port "F1" (symbPinId 71) (portName "GPIO_EMC_22") (portType INOUT))
        (port "F2" (symbPinId 72) (portName "GPIO_EMC_04") (portType INOUT))
        (port "F3" (symbPinId 73) (portName "GPIO_EMC_01") (portType INOUT))
        (port "F4" (symbPinId 74) (portName "GPIO_EMC_02") (portType INOUT))
        (port "F5" (symbPinId 75) (portName "NVCC_EMC_2") (portType INOUT))
        (port "F6" (symbPinId 76) (portName "VDD_SOC_IN_1") (portType INOUT))
        (port "F7" (symbPinId 77) (portName "VDD_SOC_IN_2") (portType INOUT))
        (port "F8" (symbPinId 78) (portName "VDD_SOC_IN_3") (portType INOUT))
        (port "F9" (symbPinId 79) (portName "VDD_SOC_IN_4") (portType INOUT))
        (port "F10" (symbPinId 80) (portName "NVCC_GPIO_2") (portType INOUT))
        (port "F11" (symbPinId 81) (portName "GPIO_AD_B0_04") (portType INOUT))
        (port "F12" (symbPinId 82) (portName "GPIO_AD_B0_07") (portType INOUT))
        (port "F13" (symbPinId 83) (portName "GPIO_AD_B0_08") (portType INOUT))
        (port "F14" (symbPinId 84) (portName "GPIO_AD_B0_09") (portType INOUT))
        (port "G1" (symbPinId 85) (portName "GPIO_EMC_10") (portType INOUT))
        (port "G2" (symbPinId 86) (portName "GPIO_EMC_23") (portType INOUT))
        (port "G3" (symbPinId 87) (portName "GPIO_EMC_11") (portType INOUT))
        (port "G4" (symbPinId 88) (portName "GPIO_EMC_03") (portType INOUT))
        (port "G5" (symbPinId 89) (portName "GPIO_EMC_05") (portType INOUT))
        (port "G6" (symbPinId 90) (portName "VDD_SOC_IN_5") (portType INOUT))
        (port "G7" (symbPinId 91) (portName "VSS_7") (portType INOUT))
        (port "G8" (symbPinId 92) (portName "VSS_8") (portType INOUT))
        (port "G9" (symbPinId 93) (portName "VDD_SOC_IN_6") (portType INOUT))
        (port "G10" (symbPinId 94) (portName "GPIO_AD_B0_11") (portType INOUT))
        (port "G11" (symbPinId 95) (portName "GPIO_AD_B0_03") (portType INOUT))
        (port "G12" (symbPinId 96) (portName "GPIO_AD_B1_14") (portType INOUT))
        (port "G13" (symbPinId 97) (portName "GPIO_AD_B0_10") (portType INOUT))
        (port "G14" (symbPinId 98) (portName "GPIO_AD_B0_05") (portType INOUT))
        (port "H1" (symbPinId 99) (portName "GPIO_EMC_12") (portType INOUT))
        (port "H2" (symbPinId 100) (portName "GPIO_SD_B0_04") (portType INOUT))
        (port "H3" (symbPinId 101) (portName "GPIO_EMC_08") (portType INOUT))
        (port "H4" (symbPinId 102) (portName "GPIO_EMC_07") (portType INOUT))
        (port "H5" (symbPinId 103) (portName "GPIO_EMC_06") (portType INOUT))
        (port "H6" (symbPinId 104) (portName "VDD_SOC_IN_7") (portType INOUT))
        (port "H7" (symbPinId 105) (portName "VSS_9") (portType INOUT))
        (port "H8" (symbPinId 106) (portName "VSS_10") (portType INOUT))
        (port "H9" (symbPinId 107) (portName "VDD_SOC_IN_8") (portType INOUT))
        (port "H10" (symbPinId 108) (portName "GPIO_AD_B0_01") (portType INOUT))
        (port "H11" (symbPinId 109) (portName "GPIO_AD_B1_13") (portType INOUT))
        (port "H12" (symbPinId 110) (portName "GPIO_AD_B1_12") (portType INOUT))
        (port "H13" (symbPinId 111) (portName "GPIO_AD_B1_08") (portType INOUT))
        (port "H14" (symbPinId 112) (portName "GPIO_AD_B0_14") (portType INOUT))
        (port "J1" (symbPinId 113) (portName "GPIO_SD_B0_02") (portType INOUT))
        (port "J2" (symbPinId 114) (portName "GPIO_SD_B0_05") (portType INOUT))
        (port "J3" (symbPinId 115) (portName "GPIO_SD_B0_01") (portType INOUT))
        (port "J4" (symbPinId 116) (portName "GPIO_SD_B0_00") (portType INOUT))
        (port "J5" (symbPinId 117) (portName "DCDC_SENSE") (portType INOUT))
        (port "J6" (symbPinId 118) (portName "NVCC_SD0") (portType INOUT))
        (port "J7" (symbPinId 119) (portName "VSS_11") (portType INOUT))
        (port "J8" (symbPinId 120) (portName "VSS_12") (portType INOUT))
        (port "J9" (symbPinId 121) (portName "VDD_SOC_IN_9") (portType INOUT))
        (port "J10" (symbPinId 122) (portName "NVCC_GPIO_3") (portType INOUT))
        (port "J11" (symbPinId 123) (portName "GPIO_AD_B1_00") (portType INOUT))
        (port "J12" (symbPinId 124) (portName "GPIO_AD_B1_06") (portType INOUT))
        (port "J13" (symbPinId 125) (portName "GPIO_AD_B1_11") (portType INOUT))
        (port "J14" (symbPinId 126) (portName "GPIO_AD_B1_15") (portType INOUT))
        (port "K1" (symbPinId 127) (portName "GPIO_SD_B0_03") (portType INOUT))
        (port "K2" (symbPinId 128) (portName "VSS_13") (portType INOUT))
        (port "K3" (symbPinId 129) (portName "DCDC_PSWITCH") (portType INOUT))
        (port "K4" (symbPinId 130) (portName "DCDC__IN_Q") (portType INOUT))
        (port "K5" (symbPinId 131) (portName "NVCC_SD1") (portType INOUT))
        (port "K6" (symbPinId 132) (portName "TEST_MODE") (portType INOUT))
        (port "K7" (symbPinId 133) (portName "PMIC_ON_REQ") (portType INOUT))
        (port "K8" (symbPinId 134) (portName "VDD_USB_CAP") (portType INOUT))
        (port "K9" (symbPinId 135) (portName "NGND_KEL0") (portType INOUT))
        (port "K10" (symbPinId 136) (portName "GPIO_AD_B1_07") (portType INOUT))
        (port "K11" (symbPinId 137) (portName "GPIO_AD_B1_01") (portType INOUT))
        (port "K12" (symbPinId 138) (portName "GPIO_AD_B1_05") (portType INOUT))
        (port "K13" (symbPinId 139) (portName "VSS_14") (portType INOUT))
        (port "K14" (symbPinId 140) (portName "GPIO_AD_B0_12") (portType INOUT))
        (port "L1" (symbPinId 141) (portName "DCDC_IN_1") (portType INOUT))
        (port "L2" (symbPinId 142) (portName "DCDC_IN_2") (portType INOUT))
        (port "L3" (symbPinId 143) (portName "GPIO_SD_B1_06") (portType INOUT))
        (port "L4" (symbPinId 144) (portName "GPIO_SD_B1_07") (portType INOUT))
        (port "L5" (symbPinId 145) (portName "GPIO_SD_B1_00") (portType INOUT))
        (port "L6" (symbPinId 146) (portName "WAKEUP") (portType INOUT))
        (port "L7" (symbPinId 147) (portName "PMIC_STBY_REQ") (portType INOUT))
        (port "L8" (symbPinId 148) (portName "USB_OTG1_DP") (portType INOUT))
        (port "L9" (symbPinId 149) (portName "VSS_15") (portType INOUT))
        (port "L10" (symbPinId 150) (portName "GPIO_AD_B0_15") (portType INOUT))
        (port "L11" (symbPinId 151) (portName "GPIO_AD_B1_02") (portType INOUT))
        (port "L12" (symbPinId 152) (portName "GPIO_AD_B1_04") (portType INOUT))
        (port "L13" (symbPinId 153) (portName "GPIO_AD_B1_10") (portType INOUT))
        (port "L14" (symbPinId 154) (portName "GPIO_AD_B0_13") (portType INOUT))
        (port "M1" (symbPinId 155) (portName "DCDC_LP_1") (portType INOUT))
        (port "M2" (symbPinId 156) (portName "DCDC_LP_2") (portType INOUT))
        (port "M3" (symbPinId 157) (portName "GPIO_SD_B1_02") (portType INOUT))
        (port "M4" (symbPinId 158) (portName "GPIO_SD_B1_03") (portType INOUT))
        (port "M5" (symbPinId 159) (portName "GPIO_SD_B1_01") (portType INOUT))
        (port "M6" (symbPinId 160) (portName "ONOFF") (portType INOUT))
        (port "M7" (symbPinId 161) (portName "POR_B") (portType INOUT))
        (port "M8" (symbPinId 162) (portName "USB_OTG1_DN") (portType INOUT))
        (port "M9" (symbPinId 163) (portName "VDD_SNVS_IN") (portType INOUT))
        (port "M10" (symbPinId 164) (portName "VDD_SNVS_CAP") (portType INOUT))
        (port "M11" (symbPinId 165) (portName "GPIO_AD_B0_02") (portType INOUT))
        (port "M12" (symbPinId 166) (portName "GPIO_AD_B1_03") (portType INOUT))
        (port "M13" (symbPinId 167) (portName "GPIO_AD_B1_09") (portType INOUT))
        (port "M14" (symbPinId 168) (portName "GPIO_AD_B0_00") (portType INOUT))
        (port "N1" (symbPinId 169) (portName "DCDC_GND_1") (portType INOUT))
        (port "N2" (symbPinId 170) (portName "DCDC_GND_2") (portType INOUT))
        (port "N3" (symbPinId 171) (portName "GPIO_SD_B1_05") (portType INOUT))
        (port "N4" (symbPinId 172) (portName "GPIO_SD_B1_09") (portType INOUT))
        (port "N5" (symbPinId 173) (portName "VSS_16") (portType INOUT))
        (port "N6" (symbPinId 174) (portName "USB_OTG1_VBUS") (portType INOUT))
        (port "N7" (symbPinId 175) (portName "USB_OTG2_DN") (portType INOUT))
        (port "N8" (symbPinId 176) (portName "VSS_17") (portType INOUT))
        (port "N9" (symbPinId 177) (portName "RTC_XTALI") (portType INOUT))
        (port "N10" (symbPinId 178) (portName "GPANAIO") (portType INOUT))
        (port "N11" (symbPinId 179) (portName "XTALO") (portType INOUT))
        (port "N12" (symbPinId 180) (portName "USB_OTG1_CHD_B") (portType INOUT))
        (port "N13" (symbPinId 181) (portName "CCM_CLK1_P") (portType INOUT))
        (port "N14" (symbPinId 182) (portName "VDDA_ADC_3P3") (portType INOUT))
        (port "P1" (symbPinId 183) (portName "VSS_18") (portType INOUT))
        (port "P2" (symbPinId 184) (portName "GPIO_SD_B1_04") (portType INOUT))
        (port "P3" (symbPinId 185) (portName "GPIO_SD_B1_08") (portType INOUT))
        (port "P4" (symbPinId 186) (portName "GPIO_SD_B1_10") (portType INOUT))
        (port "P5" (symbPinId 187) (portName "GPIO_SD_B1_11") (portType INOUT))
        (port "P6" (symbPinId 188) (portName "USB_OTG2_VBUS") (portType INOUT))
        (port "P7" (symbPinId 189) (portName "USB_OTG2_DP") (portType INOUT))
        (port "P8" (symbPinId 190) (portName "VDD_HIGH_CAP") (portType INOUT))
        (port "P9" (symbPinId 191) (portName "RTC_XTALO") (portType INOUT))
        (port "P10" (symbPinId 192) (portName "NVCC_PLL") (portType INOUT))
        (port "P11" (symbPinId 193) (portName "XTALI") (portType INOUT))
        (port "P12" (symbPinId 194) (portName "VDD_HIGH_IN") (portType INOUT))
        (port "P13" (symbPinId 195) (portName "CCM_CLK1_N") (portType INOUT))
        (port "P14" (symbPinId 196) (portName "VSS_19") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "NXP")
    (property "Manufacturer_Part_Number" "MIMXRT1061DVJ6B")
    (property "Mouser_Part_Number" "771-MIMXRT1061DVJ6B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/NXP-Semiconductors/MIMXRT1061DVJ6B?qs=BJlw7L4Cy78kRfy4mb1ozA%3D%3D")
    (property "Arrow_Part_Number" "MIMXRT1061DVJ6B")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/mimxrt1061dvj6b/nxp-semiconductors?region=nac")
    (property "Description" "ARM Cortex-M7 series Microcontroller IC 32-Bit 600MHz - External Program Memory 196-LFBGA (12x12)")
    (property "Datasheet_Link" "https://www.nxp.com/docs/en/nxp/data-sheets/IMXRT1060CEC.pdf")
    (property "symbolName1" "MIMXRT1061DVJ6B")
)
